// <auto-generated />
using System;
using CvmApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CvmApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260727143905_AdicionaCompanhiasAbertas")]
    partial class AdicionaCompanhiasAbertas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("CvmApi.Models.CompanhiaAberta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cnpj_cia");

                    b.Property<string>("CodigoCvm")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo_cvm");

                    b.Property<DateTime?>("DataRegistro")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_reg");

                    b.Property<string>("NomeComercial")
                        .HasColumnType("TEXT")
                        .HasColumnName("denom_comercial");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("denom_social");

                    b.Property<string>("SetorAtividade")
                        .HasColumnType("TEXT")
                        .HasColumnName("setor_ativ");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sit");

                    b.HasKey("Id");

                    b.ToTable("companhias_abertas");
                });

            modelBuilder.Entity("CvmApi.Models.FundoCadastro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Administrador")
                        .HasColumnType("TEXT")
                        .HasColumnName("admin");

                    b.Property<string>("CnpjAdministrador")
                        .HasColumnType("TEXT")
                        .HasColumnName("cpf_cnpj_admin");

                    b.Property<string>("CnpjFundo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cnpj_fundo");

                    b.Property<DateTime?>("DataInicioAtividade")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_ini_activ");

                    b.Property<string>("NomeComercial")
                        .HasColumnType("TEXT")
                        .HasColumnName("denom_comercial");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("denom_social");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sit");

                    b.HasKey("Id");

                    b.ToTable("fundos_cadastro");
                });

            modelBuilder.Entity("CvmApi.Models.InformeDiario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CnpjFundo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cnpj_fundo");

                    b.Property<DateTime>("DataCompetencia")
                        .HasColumnType("TEXT")
                        .HasColumnName("dt_comptc");

                    b.Property<decimal>("PatrimonioLiquido")
                        .HasColumnType("TEXT")
                        .HasColumnName("vl_patrim_liq");

                    b.Property<string>("TipoFundo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tp_fundo");

                    b.Property<decimal>("ValorCota")
                        .HasColumnType("TEXT")
                        .HasColumnName("vl_quota");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("TEXT")
                        .HasColumnName("vl_total");

                    b.HasKey("Id");

                    b.HasIndex("CnpjFundo", "DataCompetencia")
                        .IsUnique();

                    b.ToTable("informes_diarios");
                });
#pragma warning restore 612, 618
        }
    }
}
